# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header:  $

# ebuild generated by hackport 0.2.14

EAPI="3"

CABAL_FEATURES="bin lib profile haddock hscolour"
inherit haskell-cabal

DESCRIPTION="Command-line interface for browsing and searching packages documentation"
HOMEPAGE="http://github.com/serras/scion-class-browser"
SRC_URI="http://hackage.haskell.org/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~x86-macos"
IUSE=""

RDEPEND=">=dev-haskell/aeson-native-0.3.3.1
		>=dev-haskell/attoparsec-0.10
		>=dev-haskell/cabal-0.10
		=dev-haskell/cereal-0.3*
		>=dev-haskell/deepseq-1.1
		<dev-haskell/deepseq-2
		>=dev-haskell/derive-2.5
		<dev-haskell/derive-3
		=dev-haskell/ghc-paths-0.1*
		>=dev-haskell/haskeline-0.6
		>=dev-haskell/haskell-src-exts-1.11
		<dev-haskell/haskell-src-exts-2
		>=dev-haskell/http-4000
		<dev-haskell/http-5000
		>=dev-haskell/mtl-2
		>=dev-haskell/parallel-io-0.3
		=dev-haskell/parsec-3*
		=dev-haskell/tar-0.3*
		=dev-haskell/text-0.11*
		dev-haskell/utf8-string
		=dev-haskell/zlib-0.5*
		>=dev-lang/ghc-6.10.1"
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.8"
