# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header:  $

# ebuild generated by hackport 0.2.14

EAPI="3"

CABAL_FEATURES="lib profile haddock hscolour"
inherit haskell-cabal

DESCRIPTION="A static website compiler library"
HOMEPAGE="http://jaspervdj.be/hakyll"
SRC_URI="http://hackage.haskell.org/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~x86-macos"
IUSE="snap"

RDEPEND=">=dev-haskell/binary-0.5
		<dev-haskell/binary-1.0
		>=dev-haskell/blaze-html-0.4
		<dev-haskell/blaze-html-0.6
		>=dev-haskell/citeproc-hs-0.3.2
		<dev-haskell/citeproc-hs-0.4
		=dev-haskell/cryptohash-0.7*
		>=dev-haskell/hamlet-0.10.3
		<dev-haskell/hamlet-0.11
		>=dev-haskell/mtl-1
		<dev-haskell/mtl-3.0
		>=app-text/pandoc-1.6
		<app-text/pandoc-2.0
		>=dev-haskell/parsec-2.1
		<dev-haskell/parsec-3.2
		>=dev-haskell/regex-base-0.93
		<dev-haskell/regex-base-1.0
		>=dev-haskell/regex-pcre-0.93
		<dev-haskell/regex-pcre-1.0
		snap? ( >=dev-haskell/snap-core-0.5.1 
		<dev-haskell/snap-core-0.6
		>=dev-haskell/snap-server-0.5.1
		<dev-haskell/snap-server-0.6 )
		=dev-haskell/tagsoup-0.12*
		>=dev-haskell/time-1.1
		<dev-haskell/time-1.3
		>=dev-lang/ghc-6.12.1"
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.6"

src_unpack() {
    unpack $A
    cd "${S}"
    epatch "${FILESDIR}/snap.patch"
}
